name: Шаблон для issue
description: Используйте этот шаблон для создания issue в проекте Make Tarkov Competitive
title: "[Тип]: "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за вклад в проект Make Tarkov Competitive! Пожалуйста, заполните информацию ниже.

  - type: dropdown
    id: type
    attributes:
      label: Тип issue
      description: Выберите тип issue
      options:
        - Баг
        - Фича
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Важность задачи
      description: Выберите важность задачи
      options:
        - Низкая
        - Средняя
        - Высокая
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: Сроки выполнения
      description: Укажите примерные сроки выполнения задачи
      placeholder: Например, 2025-06-01 или "в течение недели"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Подробное описание
      description: Опишите issue подробно
      placeholder: Опишите проблему или идею...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Вложения
        Если у вас есть скриншоты, видео или другие файлы, которые помогут лучше понять issue, прикрепите их к этому issue.
